version: "3.8"
services:  
  postgres:
    image: postgres:12.6
    restart: always
    environment: 
      - POSTGRES_USER=emilio
      - POSTGRES_PASSWORD=emilio2k19
      - POSTGRES_DB=emilio
    ports: 
      - 5432:5432
    # volumes:
    #   - /{rutaLocal}:/var/lib/postgresql/
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "emiliocaraballo9810@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "8080:80"
    depends_on: 
      - postgres
    # volumes:
    #   - /{rutaLocal}:/var/lib/pgadmin
